image:
  file: .gitpod.Dockerfile

tasks:
  - before: curl -fsSL https://get.docker.com/rootless | sh
    command: /home/gitpod/bin/dockerd-rootless.sh --experimental --iptables=false --storage-driver vfs
  - command: clear && echo "Try 'docker' here when the daemon is up"
    openMode: split-right
